### ISSUE TITLE
talk.manageiq.org broken image

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq.org#210]
When viewing a topic, there is a broken image in the corner near the topic title.  inspecting the element points to  http://talk.manageiq.org/uploads/manageiq/51/05a46668c6419c4e.png which returns a 403 forbidden for me.

**Comment by garrett** [comment]
That was the ManageIQ glyph, cropped from the MiQ Talk graphic to a specific size, as to not have a jumping effect when it was swapped.

This is the graphic: ![](http://virtual-host-discourse.global.ssl.fastly.net/uploads/manageiq/5/6a4801e8409c26e5.png)

I didn't change anything since the site launched — and I'm not sure why anyone would. (It was probably some unintentional overlooked bug somewhere in a software upgrade, I suppose?)

The graphic was attached @ http://talk.manageiq.org/t/assets-for-the-forum-design/5 and changed in the admin section @ http://talk.manageiq.org/admin/site_settings/category/required (_logo small url_). 

This is the proper way to change site graphics (as documented by the Discourse team themselves). Specifically: 

1. Upload to that specific admin-only post.
2. Copy the resulting URL.
3. Paste the URL into the admin section, and remove the protocol and domain parts, leaving only the path & filename.
4. Save.

It's currently at `/uploads/manageiq/5/6a4801e8409c26e5.png` in that post — I'm not sure why its ID changed.

Regardless, I've fixed the problem... and documented the steps to fix it here, in case it ever happens again (for who-knows-why-reason).  :smiley:
