### ISSUE TITLE
There is no link to the Depot

### ISSUE THREAD

**Issue by hayesr** [ManageIQ/manageiq.org#414]
The site is missing a link to the Depot. I'm not sure where it should go. /cc @geertj @cybette @sergio-ocon

**Comment by cybette** [comment]
@hayesr currently it's linked from the [Community page](http://manageiq.org/community/), and the plan is to reassess the position of the Depot and perhaps "relaunch" it later on.

**Comment by hayesr** [comment]
@cybette Oh I missed that, thanks! So do we need to add anything else at this time?

**Comment by cbolz** [comment]
HiHo,
the link used to be on the front page. Now it is very well hidden. If we want people to contribute and use it, it should IMHO be more prominent.

Just my 2cents,
Christian

**Comment by cybette** [comment]
@hayesr not at the moment. We have Depot on the backlog so we'll be working on it.

@cbolz we've only had 3 contributions this year, plus currently the Depot is not visually coherent with the rest of the site. That's why we need to reposition it and brand/market it better, during which we will find a suitably prominent place for it!

Great comments, thanks :)

**Comment by hayesr** [comment]
Closing this as it seems to be addressed.
