### ISSUE TITLE
Need to add podification of images to Getting Started Guide

### ISSUE THREAD

**Issue by JPrause** [ManageIQ/manageiq.org#620]

**Comment by JPrause** [comment]
@miq-bot assign JPrause

**Comment by simaishi** [comment]
@JPrause Was this implemented?  Also I don't see mentioning of podified image in Download page either.

**Comment by JPrause** [comment]
@simaishi not sure why this was closed. Looked through history, and I see I did some cleanup of issues,....but this one was probably closed by mistake. Reopening.

**Comment by epwinchell** [comment]
@simaishi @JPrause Does this issue belong here or in https://github.com/ManageIQ/guides ?

**Comment by simaishi** [comment]
@epwinchell It belongs here, as it's about adding to Download page and possibly to "Get Started" page.

**Comment by epwinchell** [comment]
@simaishi Where does this document exist now? I can't find it in the other repos.

**Comment by epwinchell** [comment]
@JPrause @simaishi You'd probably want to ping potential volunteers here

**Comment by epwinchell** [comment]
@miq-bot add_label help wanted

**Comment by carbonin** [comment]
What exactly do we want to add for this? There's no value in pointing out the location of the images without the instructions on how to deploy them in kubernetes/openshift. Should I just link to the manageiq-pods README?

Or should we add a whole deploy doc in https://github.com/ManageIQ/manageiq.org/tree/master/site/docs/get-started similar to the vagrant/docker/public cloud bits?

**Comment by simaishi** [comment]
Not sure if we need to add to Get Started, as I think that section should just list a few that's easy to start with.

I know that's how this issue title says... but the original point discussed was that we don't talk about podified at all on our site.  I still think we should add something to download page since that page lists all images we build and it will be clear podified is one of the options if listed there

**Comment by carbonin** [comment]
Do you mean here https://www.manageiq.org/download/ ? What would we link to? It's not really a "download" as such ...

**Comment by simaishi** [comment]
yes, that page, because that's the only place I know that we have a list of images (well.. all but podified).  Maybe we can link to a document that describes how that gets used, rather than link to some images?

If there is some other place we list available images, that will work too. It's just we need to mention somewhere.

**Comment by carbonin** [comment]
Maybe a link to the pods repo in https://www.manageiq.org/docs/get-started/ would make more sense? We talk about the different options for production vs trial deployment there. Then I could write a quick sentence about kube/openshift and we don't have to put something that isn't a download on the downloads page.

What do you think?

**Comment by carbonin** [comment]
Okay, opened https://github.com/ManageIQ/manageiq.org/pull/783. Not sure who has merge rights here ... @epwinchell @cybette ?
