### ISSUE TITLE
Download page image size not being updated

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/manageiq.org#694]
The image sizes on the download page are often out-of-date. We need a way to keep them up-to date!

cc @cybette @JPrause

**Comment by Fryguy** [comment]
A while ago @simaishi and I had the idea to query something from releases.manageiq.org live, and then the file sizes would just be some relatively simple javascript code, with a placeholder spinner.  I believe we found a HEAD request can retrieve the file size via the header, so that might be a possibility, but cross-origin problems make that hard to develop locally.
